### PR TITLE
Update bunsenlabs-text-flame.svg

### PR DESCRIPTION
**Pull request by hhhorb**
Set all element's color to #333333ff.

### CODE REVIEW

**Comment by johnraff** [comment]
@hhhorb that you're sending this as a pull request, rather than making the change directly, means that you'd like a second opinion? (Not my dept. I'm afraid.)

**Comment by capn-damo** [comment]
@hhh It is for consistency with the rest of the themeing? No problem with me for you to merge it.

**Comment by hhhorb** [comment]
I thought y'all needed to update the changelog. Merging.

**Comment by johnraff** [comment]
> I thought y'all needed to update the changelog.

The "procedure" is to post an issue in the devs area, which will be closed (by @2ion in this case) when the version is bumped. (Of course it might be left till some other changes have gone in.)

**Pull request merged**
